### ISSUE TITLE
Update to las2peer v1.1.0 (Java 14)

### ISSUE THREAD

**Issue by phil-cd** [rwth-acis/las2peer-template-project#22]
Once the new las2peer version 1.1.0 is released, the template project should also be updated in order to help the service maintainers to update their services easily.
Things that definitely need to be changed:
- ~~openjdk version used in the Dockerfile~~ There is no dockerfile
- build.xml should check for Java 14 instead of 1.8 (https://github.com/rwth-acis/las2peer-template-project/blob/master/build.xml#L58); this is similar to the build.xml files in the main las2peer repository
- .travis.yml needs to be updated (also similar to main las2peer)
- ReadMe hint on version of Java used

Please note, that this list might be incomplete.

**Comment by pedela** [comment]
Please also don't forget to update the other two dependencies (https://libraries.io/github/rwth-acis/las2peer-template-project) :)

**Comment by phil-cd** [comment]
Using the following branch: https://github.com/rwth-acis/las2peer-template-project/tree/las2peer-1.1.0

**Comment by phil-cd** [comment]
The build.xml, .travis.yml and the ReadMe java version hint were adjusted in commit 9c630ecc76f5fea56dfc2ec48860083808ecd367.
Commit 0d71beea928d935ed50485d205d426795c5774ab updates the version of las2peer used to 1.1.0.
JUnit and jacoco (the other two dependencies) were update in cf45a456b3068475b7d17dcae73f2ee03a400d0b.
