### ISSUE TITLE
[BUG] Can't open las2peer node frontend

### ISSUE THREAD

**Issue by lakhoune** [rwth-acis/las2peer-template-project#32]
I was not able to access the las2peer node frontend after launching the service. 

**Logs**
The logs on the node only show ``File not found: '/webapp/images/manifest/icon-192x192.png'`` while all other resources load just fine when inspecting the network tab in the browser

**Steps to reproduce**
1. clone repository
2. build the service using gradle
3. launch localhost:8080 in your browser

**Comment by ChenkunZhang** [comment]
I could launch the  localhost:8080  in the browser now

**Comment by lakhoune** [comment]
If you fix an issue, please describe how you fixed it and then close the issue I will close it for you this time
